export const siteConfig = {
  name: "Agatha Pinheiro",
  role: "Desenvolvimento Web",
  slogan: "Tecnologia feita para impulsionar negócios.",
  email: "agathapdev@gmail.com",
  whatsapp: "5521987103449",
  instagram: "@agathapinheiro.dev",
  instagramUrl: "https://instagram.com/agathapinheiro.dev",
  github: "",
  linkedin: "",
  siteUrl: "",
};

export const services = [
  { number: "01", icon: "web", title: "Desenvolvimento web", description: "Sites modernos, responsivos e personalizados para apresentar sua marca com clareza." },
  { number: "02", icon: "system", title: "Sistemas personalizados", description: "Soluções digitais construídas de acordo com os processos e necessidades do seu negócio." },
  { number: "03", icon: "landing", title: "Landing pages", description: "Páginas estratégicas para comunicar uma oferta e conduzir visitantes à ação." },
  { number: "04", icon: "automation", title: "Automações", description: "Soluções para reduzir tarefas manuais e tornar a operação mais fluida." },
  { number: "05", icon: "maintenance", title: "Manutenção e melhorias", description: "Correções, atualizações e evolução contínua para projetos já existentes." },
  { number: "06", icon: "ai", title: "Inteligência Artificial & Integrações", description: "Implementação de inteligência artificial e integrações entre ferramentas para automatizar processos e tornar seu negócio mais inteligente." },
  { number: "07", icon: "system", title: "Integrações de Sistemas", description: "Conexão entre plataformas, ferramentas e sistemas para centralizar informações e automatizar processos." },
  { number: "08", icon: "web", title: "Consultoria e Soluções Digitais", description: "Análise das necessidades do negócio para definir estratégias e soluções digitais mais eficientes." },
];

export const processSteps = [
  ["01", "Conversa", "Entender necessidade, objetivo e contexto."],
  ["02", "Planejamento", "Definir estrutura, funcionalidades e solução."],
  ["03", "Desenvolvimento", "Construir a solução com atenção aos detalhes."],
  ["04", "Ajustes", "Validar, ouvir e aperfeiçoar o resultado."],
  ["05", "Entrega", "Finalizar e disponibilizar o projeto."],
];

export type Project = {
  id: string; title: string; category: string; shortDescription: string; description: string;
  challenge: string; solution: string; features: string[]; technologies: string[];
  status: string; images: string[]; demoUrl: string; githubUrl: string;
};

export const projects: Project[] = [
  { id: "dg-moura-cell", title: "DG Moura Cell", category: "DESENVOLVIMENTO WEB / SISTEMA / SOLUÇÕES DIGITAIS", shortDescription: "Sistema de gestão desenvolvido sob medida para a DG Moura Cell, reunindo em uma única plataforma as principais operações da loja e da assistência técnica.", description: "Sistema de gestão desenvolvido sob medida para a DG Moura Cell, reunindo em uma única plataforma as principais operações da loja e da assistência técnica.", challenge: "A rotina da DG Moura Cell envolve diferentes processos acontecendo ao mesmo tempo: atendimento de clientes, serviços de assistência técnica, controle de produtos, estoque e acompanhamento das atividades.\n\nA necessidade era ter uma solução que centralizasse essas informações e facilitasse o controle da operação, tornando o gerenciamento mais organizado e prático.", solution: "Foi desenvolvido um sistema de gestão personalizado em Java Swing, conectado a um banco de dados em nuvem, permitindo centralizar as informações da empresa e organizar diferentes áreas da operação em uma única solução.\n\nA plataforma foi estruturada de acordo com as necessidades reais da loja, reunindo ferramentas para gerenciamento de clientes, serviços, estoque, produtos, fila de trabalho e relatórios.", features: ["Cadastro de clientes — Cadastro e gerenciamento das informações dos clientes, mantendo os dados organizados e acessíveis dentro do sistema.", "Fila de trabalho — Organização dos serviços e atendimentos da assistência técnica, facilitando o acompanhamento das atividades que precisam ser realizadas.", "Estoque — Controle de produtos e quantidades, permitindo acompanhar as informações do estoque de forma centralizada.", "Relatórios — Geração e acompanhamento de relatórios para auxiliar no controle da operação e na análise das informações do negócio.", "Produtos e serviços — Organização dos produtos comercializados e dos serviços oferecidos pela assistência técnica.", "Banco de dados em nuvem — Centralização das informações em banco de dados em nuvem, mantendo os dados organizados e disponíveis para a aplicação."], technologies: ["Java", "Java Swing", "Banco de dados em nuvem"], status: "Um sistema desenvolvido especificamente para a operação da DG Moura Cell, centralizando clientes, serviços, estoque, produtos, fila de trabalho e relatórios em uma única solução.\n\nMais do que um sistema genérico, o projeto foi construído considerando as necessidades reais da operação da empresa, permitindo que a tecnologia acompanhe a rotina do negócio.", images: [], demoUrl: "", githubUrl: "" },
  { id: "alebronze", title: "Alebronze", category: "SISTEMA / GESTÃO / SOLUÇÕES DIGITAIS", shortDescription: "Sistema de gestão desenvolvido para um estúdio de bronze, criado para centralizar a rotina do negócio e facilitar o gerenciamento de clientes, sessões, agendamentos, financeiro e operação.", description: "Sistema de gestão desenvolvido para um estúdio de bronze, criado para centralizar a rotina do negócio e facilitar o gerenciamento de clientes, sessões, agendamentos, financeiro e operação.", challenge: "A rotina de um estúdio de bronze envolve diferentes processos que precisam estar organizados e conectados: cadastro de clientes, agendamentos, acompanhamento das sessões, controle financeiro e gerenciamento das informações do negócio.\n\nA necessidade era reunir essas operações em um único sistema, tornando a gestão mais prática e permitindo que as informações importantes estivessem centralizadas e organizadas.", solution: "Foi desenvolvido um sistema de gestão personalizado para a realidade de um estúdio de bronze.\n\nA plataforma centraliza as principais atividades da operação, permitindo administrar clientes, organizar agendamentos, acompanhar sessões, controlar informações financeiras e consultar dados importantes do negócio em um único ambiente.\n\nA solução foi pensada para simplificar a rotina e transformar diferentes processos de gestão em uma experiência mais organizada e fácil de acompanhar.", features: ["Cadastro de clientes — Cadastro e gerenciamento das informações dos clientes, mantendo os dados organizados e acessíveis dentro do sistema.", "Agendamento — Organização dos horários e agendamentos do estúdio, facilitando o controle da agenda e dos atendimentos.", "Controle de sessões — Acompanhamento das sessões realizadas pelos clientes, permitindo manter o histórico e as informações dos atendimentos organizados.", "Financeiro — Controle das informações financeiras do negócio, auxiliando no acompanhamento das movimentações e resultados.", "Gestão da operação — Centralização das informações necessárias para acompanhar a rotina do estúdio e facilitar o gerenciamento das atividades.", "Relatórios — Visualização de informações e indicadores para auxiliar no acompanhamento da operação e na tomada de decisões."], technologies: [], status: "Uma solução desenvolvida sob medida para centralizar a gestão de um estúdio de bronze, reunindo clientes, agendamentos, sessões, financeiro e informações da operação em um único sistema.\n\nO projeto transforma diferentes processos do dia a dia em uma estrutura mais organizada, facilitando o acompanhamento da rotina e dando mais controle sobre as informações do negócio.", images: [], demoUrl: "", githubUrl: "" },
  { id: "atelie-malaka", title: "Ateliê Malaka", category: "SISTEMA / GESTÃO / SOLUÇÕES DIGITAIS", shortDescription: "Sistema de gestão desenvolvido para uma loja de roupas, reunindo ferramentas para cadastro, vendas, organização e atendimento em uma única solução.", description: "Sistema de gestão desenvolvido sob medida para o Ateliê Malaka, centralizando diferentes processos da loja em um único ambiente e facilitando o controle da operação, das vendas e do atendimento aos clientes.", challenge: "A rotina de uma loja de roupas envolve diferentes processos acontecendo ao mesmo tempo, desde o cadastro e organização de produtos e clientes até o registro das vendas e o acompanhamento dos resultados. Além da operação interna, também existe a necessidade de manter um atendimento mais ágil e facilitar a comunicação com os clientes. A proposta foi centralizar essas atividades em um único sistema, tornando a rotina da loja mais organizada e prática.", solution: "Foi desenvolvido um sistema de gestão personalizado para o Ateliê Malaka, reunindo ferramentas para organizar clientes e produtos, registrar vendas, acompanhar resultados e facilitar o relacionamento com os clientes. A solução concentra diferentes etapas da operação em um único ambiente, permitindo que a loja tenha mais controle sobre suas informações e sobre o processo de vendas.", features: ["Cadastro de clientes", "Cadastro de produtos", "Relatórios de vendas", "Caderno", "PDV", "Integração com WhatsApp"], technologies: [], status: "Sistema de gestão desenvolvido sob medida para a operação do Ateliê Malaka.", images: [], demoUrl: "", githubUrl: "" },
  { id: "sistema-processos", title: "Sistema de Processos", category: "SISTEMA / GESTÃO / AUTOMAÇÃO", shortDescription: "Sistema desenvolvido para centralizar o acompanhamento de processos, controlar prazos e organizar informações em um único ambiente.", description: "Uma solução de gestão desenvolvida para facilitar o acompanhamento de processos, centralizar informações e automatizar o controle de prazos, permitindo uma visão mais organizada das atividades e dos documentos relacionados.", challenge: "O acompanhamento de processos pode envolver grande volume de informações, diferentes prazos e diversas atualizações ao longo do tempo. Sem uma estrutura centralizada, torna-se mais difícil identificar situações próximas do vencimento, acompanhar alterações e manter um histórico organizado. O desafio foi criar uma solução que reunisse essas informações e facilitasse o acompanhamento de cada processo.", solution: "Foi desenvolvido um sistema de gestão de processos capaz de centralizar informações, acompanhar prazos, organizar atualizações e gerar alertas para situações que exigem atenção. A plataforma também reúne recursos de busca, filtros, relatórios, importação e exportação de dados, tornando o acompanhamento mais organizado e eficiente.", features: ["Cadastro e gerenciamento de processos", "Importação de processos por planilha", "Acompanhamento e atualização de processos", "Controle de prazos", "Alertas de vencimento", "Controle de envio de e-mails", "Busca e filtros", "Dashboard e indicadores", "Exportação para Excel", "Impressão de documentos e relatórios"], technologies: [], status: "Sistema desenvolvido para centralizar o acompanhamento de processos, prazos e informações operacionais.", images: [], demoUrl: "", githubUrl: "" },
];

export const testimonials = [
  ["Feedback 01", "A comunicação durante o projeto foi clara desde o início. A solução foi desenvolvida pensando nas necessidades do negócio, com atenção aos detalhes e à experiência de quem vai utilizar."],
  ["Feedback 02", "O projeto transformou uma necessidade que parecia complexa em uma solução mais organizada, prática e fácil de utilizar. O resultado trouxe mais clareza para o processo."],
  ["Feedback 03", "Gostei principalmente da atenção aos detalhes e da preocupação em entender o problema antes de começar a desenvolver. O resultado ficou alinhado ao que o projeto precisava."],
];

export const faqs = [
  ["Você trabalha com projetos personalizados?", "Sim. Cada projeto começa com uma conversa para entender o contexto e definir uma solução adequada à necessidade apresentada."],
  ["Você desenvolve sites responsivos?", "Sim. Os projetos são pensados para funcionar com clareza em diferentes tamanhos de tela."],
  ["Você cria landing pages?", "Sim. Landing pages podem ser desenvolvidas para apresentar uma oferta, serviço ou campanha com foco em conversão."],
  ["Você desenvolve sistemas personalizados?", "Sim. Sistemas podem ser planejados a partir dos processos e objetivos específicos de cada negócio."],
  ["Você trabalha com automações?", "Sim. A automação pode ajudar a reduzir tarefas manuais e organizar fluxos repetitivos."],
  ["Você faz manutenção em sistemas existentes?", "Sim. É possível avaliar correções, atualizações e melhorias em projetos existentes."],
  ["Como funciona o orçamento?", "Depois de entender o projeto, as necessidades e o escopo, conversamos sobre a melhor forma de seguir. O orçamento é personalizado."],
  ["Como posso entrar em contato?", "Você pode usar o formulário desta página para abrir uma conversa no WhatsApp ou enviar um e-mail diretamente."],
];
